name: fittrack
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.2.0
  provider: ^6.0.2
  get: ^4.6.1
  http: ^0.13.4
  flutter_svg: ^1.0.3
  google_fonts: ^2.2.0
  flutter_launcher_icons: ^0.9.2
  google_mobile_ads: ^1.0.1
  rename: ^2.0.1
  flutter_native_splash: ^2.0.2
  
flutter_native_splash:
  color: "#ffffff"
  image: "assets/logo.png"
  android: true
flutter_icons:
  android: true
  image_path: "assets/logo2.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo3.png"
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0
  bottom_navy_bar: ^6.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/
  
